### ISSUE TITLE
Go-live checklist

### ISSUE THREAD

**Issue by NoxHarmonium** [agiledigital-labs/aws-durable-lambda#81]
This issue will track the things we need to sort out before we release the library to NPM:

- [ ] Decide the point where the library is release ready and put the issues in the list below
- [ ] Decide on NPM repo and obtain token
- [ ] https://github.com/agiledigital-labs/aws-durable-lambda/issues/80
- [ ] https://github.com/agiledigital-labs/aws-durable-lambda/issues/44
- [ ] https://github.com/agiledigital-labs/aws-durable-lambda/issues/42
- [ ] https://github.com/agiledigital-labs/aws-durable-lambda/issues/41 (maybe)
